authorName: default
experimentName: centerloss_params_pytorch
trialConcurrency: 1
maxExecDuration: 2h
maxTrialNum: 10

#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  builtinTunerName: TPE
  classArgs:
    optimize_mode: maximize
trial:
  command: python nni_search.py
  codeDir: .
  gpuNum: 1
localConfig:
  useActiveGpu: true